error: [autil_vec_set] Index out of bounds (3)
